#171380746 User descriptive signup validation errors
atlp-rwanda/stackup2-barefoot-backend pull request #15
Opened 2020-03-04 00:00 UTC by muchristian

What does this PR do?
for descriptive user signup validation errors

Description of Task to be completed?
add src/middlewares/authValidation.js middleware
add src/services/authValidationService.js service
add src/utils/validateError.js Util

How should this be manually tested?
- clone the project
- open your project in cmd, and then write _npm install_ to install packages
- while signing up try to write invalid text on email for instance.
- run the project by writing in cmd _npm start_ . 
- test signup endpoint in postman for instance, and see the output. Actually will return error because email is invalid as aforementioned.

Any background context you want to provide?
N/A

What are the relevant pivotal tracker stories?
#171380746

2020-03-11 09:04 UTC, ricahcyuzuzo requested changes
Would you solve the coverage issue?

2020-03-11 09:23 UTC, Muhire-Josue commented on src/controllers/authentication.controller.js
> +        return errorResponse(res, 409, 'user with the provided email exist');
can you use the `../utils/customMessages.js` and `../utils/statusCodes.js`. You can just move the status code and error message there and call it here.

2020-03-11 09:25 UTC, Muhire-Josue commented on src/middlewares/authValidation.js
> +    return res.status(400).json({ status: 400, error: messages });
same thing here, you can move that status code in `../utils/statusCodes.js` then call it here.

2020-03-11 09:36 UTC, Muhire-Josue commented on tests/authentication.test.js
>  // Signup
could you remove this comment please?

2020-03-11 09:38 UTC, Muhire-Josue commented on tests/authentication.test.js
> +        expect(res.status).to.equal(409);
Also you can use the status from `../utils/statusCodes.js` here.

2020-03-11 09:44 UTC, Muhire-Josue reviewed
You did a great job here, congratulations. We have predefined response messages and status code in `../utils/customMessage.js` and `../utils/statusCodes.js` could you refer to those in every response and in the tests. 
                 `ex: successResponse(res, message.userCreated, statusCode.ok)`
                  `ex: expect(res.body.status).to.equal(statusCode.conflict)`

2020-03-11 14:44 UTC, kipropbrian approved these changes

2020-03-11 16:28 UTC, Ugizwenayo-Divine reviewed
You really did a good job Christian but I suggested that
- you remove that authentication.js file in src/routes/api as it is empty
- you also remove mocksupdata file within tests folder as Emmanuel said that He didn't use it and he is the one who created it
- Finally remember to fix those hound issues

good work by the way

2020-03-11 16:28 UTC, Muhire-Josue approved these changes
LGTM

2020-03-11 16:30 UTC, Muhire-Josue reviewed
Can you take care of those hound violations

2020-03-11 16:53 UTC, ricahcyuzuzo approved these changes
Good Job

2020-03-11 18:01 UTC, the22mastermind requested changes
Good Job @muchristian check out the comments I left. Keep up the good work.

2020-03-11 18:01 UTC, the22mastermind commented on tests/authentication.test.js
> +        expect(res.status).to.equal(statusCodes.badRequest);
Could you also expect an error message and pass the appropriate message?

2020-03-11 18:01 UTC, the22mastermind commented on tests/authentication.test.js
> +        expect(res.status).to.equal(statusCodes.conflict);
Same comment as above

2020-03-11 18:01 UTC, the22mastermind commented on src/middlewares/validations.js
> +        firstName: validationMethods(/^[a-zA-Z]\S+$/, { 'string.pattern.base': 'firstName must consists of alphabets only and no whitespace' }),
Could you move all these custom messages in customMessages.js and import them here?

2020-03-11 18:01 UTC, the22mastermind commented on tests/authentication.test.js
> +        expect(error).to.equal('firstName must consists of alphabets only and no whitespace');
Could you create these custom messages in customMessages.js and import them here? The same way you used statusCodes.

2020-03-12 15:07 UTC, mifeille commented on src/utils/customMessages.js
> +  invalidEmail: 'email must consists of alphabets, numbers and @ sign',
Please start all your error messages with capital letters and for the email, you can give an example of how the email should look like (for ex: example@email.com)

2020-03-12 15:07 UTC, mifeille commented on src/utils/customMessages.js
> +  alreadyExistEmail: 'user with the provided email exist',
Please change this error to this: The user with the provided email already exists.

2020-03-12 15:07 UTC, mifeille commented on src/utils/customMessages.js
> +  invalidFirstname: 'firstName must consists of alphabets only and no whitespace or special characters',
Please change this error to this and do it for the last name.
The first name must consist of alphabets only, no whitespaces or special characters.

2020-03-12 19:16 UTC, Ugizwenayo-Divine reviewed
why did you remove run seed from test script
I think this findUserIfEmail exist do the same as findUserByEmail
why did you remove comments that were explaining what a function do?

2020-03-13 09:54 UTC, merged