validate new password
atlp-rwanda/stackup2-barefoot-backend pull request #27
Opened 2020-03-14 18:58 UTC by Ugizwenayo-Divine

#### What does this PR do?
- validate a new password before resetting the password

#### Description of Task to be completed?
- created validatePassword function in middlewares/validation.js file
- created passwordResetValidation function in middlewares/authValidation.js
- called passwordResetValidation middleware before updating password

#### How should this be manually tested?
- After cloning the project repo, run `npm i` inside the cloned repo folder
- Make sure to provide all values for variables under `#Development database`
- Finally, run the following commands respectively:
`git pull`
`git checkout bg-validate-updated-password`
`npx sequelize-cli db:create`
`npx sequelize-cli db:migrate`
- make sure you have some data in users table
- npm run dev
##### In postman
- run `http://localhost:3000/api/auth/resetpassword` 
- then `http://localhost:3000/api/auth/resetpassword/token`
 provide an invalid password, you must get "Password should consists of alphabets, numbers and at least 8 characters minimum" message
#### Any background context you want to provide?
- make sure node is installed on your machine

#### What are the relevant pivotal tracker stories?
N/A

#### Screenshots (if appropriate)
N/A

2020-03-15 08:07 UTC, muchristian approved these changes
you did a great job, but you still have to fix code climate issue

2020-03-16 20:20 UTC, descholar-ceo requested changes
You did well @Ugizwenayo-Divine but I have a little suggestion for you, try to edit the existing function of validation which was already there, to create a new one I don't think it as a good idea

2020-03-16 20:20 UTC, descholar-ceo commented on src/middlewares/authValidation.js
> +const passwordResetValidation = async (req, res, next) => {
I think there is no point of creating the second validation function, you should use the existing validation function which was created to validate signup, and then you edit that function to make it adapt to your needs

2020-03-17 14:46 UTC, Muhire-Josue reviewed
Can you include screenshots of `responses` from postman, especially error messages. you can add those screenshots in your PR under `Screenshots (if appropriate)`

2020-03-17 14:49 UTC, Muhire-Josue commented on tests/authentication.test.js
> +      password: 'segsese145'
This is very "plain text", can you create a `mockData` for password in `tests/data/mockData.js`

2020-03-18 09:17 UTC, Muhire-Josue reviewed
Could you include a label on this PR?

2020-03-18 09:17 UTC, descholar-ceo approved these changes

2020-03-18 10:35 UTC, the22mastermind commented
@Ugizwenayo-Divine You did a great job. I would like to suggest you include a middleware that checks token validity on this route `/api/auth/resetpassword/token`, that way when someone takes longer to reset their password and the token expires, they will receive an appropriate message. Keep it up.

2020-03-19 07:13 UTC, Muhire-Josue reviewed
LGTM

2020-03-19 12:15 UTC, mifeille commented on src/middlewares/validations.js
> +      // jwt.verify(token, process.env.JWT_KEY);
Please remove this commented line.

2020-03-19 19:50 UTC, merged