#171380740 integrate coveralls
atlp-rwanda/stackup2-barefoot-backend pull request #3
Opened 2020-02-26 12:38 UTC by Ugizwenayo-Divine

#### What does this PR do?
- integrate coveralls code coverage service

#### Description of Task to be completed?
- install coveralls 
- add stackup2-barefoot repo on coveralls
- create .coveralls.yml file

#### How should this be manually tested?
- After the tests are written, it should give you the coverage of the tested lines.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
 [#171380740] (https://www.pivotaltracker.com/story/show/171380740)

2020-02-26 12:52 UTC, ricahcyuzuzo reviewed
Hey Divine, Where is the badge of coveralls in your readme file? I'd like to request a badge in a readme file

2020-02-26 13:04 UTC, descholar-ceo requested changes
### My Suggestions

* I suggest you to change the `in-progress` badge into `WIP` on this PR
* I suggest also to install `nyc` package which calls npm scripts to run tests and report the coverage
* I suggest you to add scripts in `package.json` to run coverage,

2020-02-26 16:24 UTC, Ugizwenayo-Divine commented
> Hey Divine, Where is the badge of coveralls in your readme file? I'd like to request a badge in a readme file
I have added the badge in readme 
thank you

2020-02-26 17:56 UTC, descholar-ceo reviewed
Cool, I see that you tried to implement all of the suggestions which is good, but I pulled your branch, and the one which has a sample test, unfortinately, I am no seeing any coverage.

Could you try to see work on it and figure out what is a problem?

2020-02-26 17:56 UTC, descholar-ceo submitted a review, later dismissed

2020-02-26 18:09 UTC, since9629 approved these changes
Great job @Ugizwenayo-Divine

2020-02-27 13:32 UTC, descholar-ceo approved these changes
LGTM

2020-02-27 14:06 UTC, Muhire-Josue commented on .coveralls.yml
> +repo_token: IDIbRhOhSENsSUw1oXoka4q0WbtjJZWcs
I think you need to fix this next line issue

2020-02-27 14:07 UTC, Muhire-Josue approved these changes
Great work Divine. I left a little comment.

2020-02-27 15:37 UTC, muchristian approved these changes
good job @Ugizwenayo-Divine

2020-02-27 18:50 UTC, Muhire-Josue approved these changes
Looks good to me.

2020-02-28 08:02 UTC, mifeille approved these changes

2020-02-28 08:04 UTC, merged