#171380755 Email and in-app notifications
atlp-rwanda/stackup2-barefoot-backend pull request #39
Opened 2020-03-28 11:38 UTC by Muhire-Josue

#### What does this PR do?

- It provides both in-app and Email notifications upon user create trip request

#### Description of Task to be completed?

- When a user creates a trip request they get an email notification about their trip request.

- A user can also disable email notifications so that they don't receive email notifications anymore.

- A manager is able to get the in-app notifications.

#### How should this be manually tested?

- `git clone https://github.com/Stackup-Rwanda/stackup2-barefoot-backend.git`
- `cd stackup2-barefoot-backend`
- `npm install`
- Use `.env.example` as reference for environment variables
- In case you don't have a functional database for this project, run `npm run create-db`
- `npm run migrations`
- `npm run dev`
- At this point, the server must be running and the application should be connected to the database and all the tables in the database are created.
- Signup using this URL `localhost:3000/api/auth/signup` use this sample object 
```
{
	"firstName": "YOUR_FIRST_NAME",
	"lastName":"YOUR_LAST_NAME",
	"address":"YOUR_ADDRESS",
	"username":"YOUR_USERNAME",
	"password":"YOUR_PASSWORD",
	"email":"YOUR_EMAIL",
	"gender":"YOUR_GENDER"
}
```
- Login in order to verify your account using this URL `localhost:3000/api/auth/login` use this sample object

```
"email":"YOUR_EMAIL",
"password":"YOUR_PASSWORD"

```
- create a trip using this URL `localhost:3000/api/trips` use this object sample 
```
{
	"travelFrom": "kigali",
    "travelTo": "Butare",
    "travelDate": "2020-05-14",
    "travelReason": "business meeting",
    "travelType": "one-way",
    "accommodation": true
}

```

- Use this URL to disable email notifications `localhost:3000/api/auth/email/disable/`

- If you are a manager in this app use this URL to get in-app notifications `localhost:3000/api/trips/inapp/notification/`

#### Any background context you want to provide?

- When you signup please provide a real email address that you can access because notifications will be sent that email address that you provided during signup.

#### What are the relevant pivotal tracker stories?

- [171380755](https://www.pivotaltracker.com/story/show/171380755)

#### Screenshots (if appropriate)
![disable email](https://user-images.githubusercontent.com/37122177/77662143-2b3cea00-6f84-11ea-9ed2-23e1f10630a6.PNG)
![email notification](https://user-images.githubusercontent.com/37122177/77662150-2d06ad80-6f84-11ea-9867-f208a62d35dd.PNG)
![in-app](https://user-images.githubusercontent.com/37122177/77662159-2e37da80-6f84-11ea-9219-b90e21ce41d4.PNG)

2020-04-10 10:58 UTC, Ugizwenayo-Divine reviewed
Good job Josue
Would you please solve those 3 issues

2020-05-05 07:45 UTC, Ugizwenayo-Divine reviewed
Would you help me with this issue
I am getting this error while creating a trip request. 
![Josue](https://user-images.githubusercontent.com/52660542/81044640-6d452f80-8e50-11ea-9cd8-9096c40e663a.PNG)

2020-05-05 15:01 UTC, Ugizwenayo-Divine reviewed
I would suggest to put enough description on your PR:
- what's the problem here
![Josue](https://user-images.githubusercontent.com/52660542/81081123-38a39900-8e8d-11ea-9dd6-8fffb3b708ea.PNG)

2020-05-07 08:36 UTC, Ugizwenayo-Divine reviewed
Please, would you solve CI failing issue and also the code climate issue

2020-05-10 19:31 UTC, the22mastermind commented on README.md
> +| api/auth/disable?mode=inapp | POST | 200 OK | It enables/disables inApp notifications |
Please change the request method to GET.

2020-05-10 19:32 UTC, the22mastermind commented on README.md
> +| api/auth/disable?mode=email | POST | 200 OK | It enables/disables email notifications |
Same here

2020-05-10 19:35 UTC, the22mastermind commented on src/controllers/authentication.controller.js
> +  updateIsVerifiedOrDisableNotification
Could you rename this function to maybe `updateIsVerifiedOrUpdateNotification` since the part of notifications deals with both disable and enable?

2020-05-10 19:44 UTC, the22mastermind commented on src/controllers/comment.controller.js
> +        await createInAppNotification(currentUser, requestId, 4);
Could you use the variables you created in `notificationTypes.utils` instead of `4`?

2020-05-10 19:47 UTC, the22mastermind commented on src/controllers/notification.controller.js
> +    if (role === 'manager') {
Instead of `manager` use the variable in userRoles.utils.

2020-05-10 20:20 UTC, the22mastermind commented on src/services/authentication.service.js
> +  static updateIsVerifiedOrDisableNotification = async (value, status) => {
Could you change the name of this method and update it's JSDoc to reflect what it does exactly?

2020-05-10 20:25 UTC, the22mastermind commented on src/services/request.service.js
> +  // static async getTripRequestsFromRequesterId(ids) {
Remove this commented code.

2020-05-10 20:29 UTC, the22mastermind commented on src/utils/disableNotification.util.js
> +const disableNotification = async (mode, id) => {
Could you add empty lines before this function and after it, to separate it from the destructured statements above and the export statement below?

2020-05-10 20:33 UTC, the22mastermind commented on src/utils/getInappNotification.js
> +const getInAppNotificationForManager = async (id, notificationStatus) => {
Please remove the commented code in this function.

2020-05-10 20:37 UTC, the22mastermind commented on tests/controllers/notifications.test.js
> +describe('Notifications Tests', () => {
Could you delete this file since it doesn't contain any test?

2020-05-10 20:58 UTC, the22mastermind reviewed
@Muhire-Josue Great job!
Please check out the comments I left.
Additionally, the endpoint for enabling and disabling notifications uses GET. Don't you think it should use PATCH? Also check this endpoint in your PR description, your README and in routes to make sure they are matching.

Finally, I think this message should be changed to maybe `Here are all your unread notifications` since it's them we are retrieving not trip requests.
![Screenshot from 2020-05-10 20-48-40](https://user-images.githubusercontent.com/45935765/81510352-4f287500-9311-11ea-8f2c-2bea75519c79.png)

2020-05-11 22:46 UTC, descholar-ceo submitted a review, later dismissed
This is great @Muhire-Josue, you have done a tremendous job, special congrats. However, I have noticed something we talked about on standup, you are still using that old way of writing repeatedly methods of interacting with the DB. Could you move those methods in CrudRepository object?

2020-05-13 09:31 UTC, descholar-ceo requested changes
1. It is difficult to find the endpoints you worked on. I guess you documented them in swagger and readme files but you should make your PR description holds all necessary information. So could you add the endpoints in your PR description? Refer to this documentation [Andela best practices](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices), take a look on the PR section

2. In your PR's `how should this be manually tested` section, the steps you provided don't lead to your branch testing, because after cloning the repo, (wht you clone is the develop branch) not yours. So, all of the steps you provided lead to testing of develop branch. Could you take care of that?
![Screenshot from 2020-05-13 11-34-12](https://user-images.githubusercontent.com/56886064/81796440-bad73180-950d-11ea-9565-0241c47ec6d3.png)

2020-05-13 10:28 UTC, descholar-ceo requested changes
@Muhire-Josue congrats that you worked hard to realise this task, however, I have few concerns:

A. It looks like you did these three endpoints : 
`GET      /api/auth/disable?mode=inapp`
`GET     /api/trips/inapp/notification/`
`GET    /api/trips/inapp/notification?status=unread`

===> Since there is an endpoint of disabling notifications, then we need another one for enabling them back. Could you work on it too?

B. I think whenever a requester creates a request, the barefoot nomad was supposed to send him email notification, I created one but I did not get any email, are you sure that it works? If so, what did I miss? 

### INFO: 

1. When I signed up I used my live email `emmanuellamugi@gmail.com` this is a requester who requested the trip

2. The manager of that requester email is this one `emmamugira@gmail.com` which is my email too and I use it, (means it is valid), but this manager did not get the email notification

C. I read your endpoint documentation from README.md file and I found this: 
![Screenshot from 2020-05-13 12-30-39](https://user-images.githubusercontent.com/56886064/81802007-9717e980-9515-11ea-8c53-ec374bb28dca.png)
Are you sure all of those endpoints are POST? If so, you should update you PR description, it does not match that documentation.


D. Finally, what is the use of this table? 
![Screenshot from 2020-05-13 13-18-35](https://user-images.githubusercontent.com/56886064/81806146-5c657f80-951c-11ea-994c-50fb0ad1a5d3.png)



===> Except those comments above, other things are cool, congratulation again for making it this far!

2020-05-20 06:59 UTC, descholar-ceo reviewed
Could you solve the conflicts this branch has with the base branch?

2020-05-21 03:21 UTC, the22mastermind commented
@Muhire-Josue let me know when you finish resolving those conflicts I review your PR.

2020-05-21 11:08 UTC, Ugizwenayo-Divine reviewed
great job Josue
but would you help me with those route:
- PATCH `http://localhost:3000/api/trips/inapp/notification?status=unread` I'm getting an error `The requested resource was not found`
-GET  `http://localhost:3000/api/auth/disable?mode=email` I'm getting the same error

2020-05-21 12:01 UTC, Ugizwenayo-Divine reviewed
Well done!!!
- Please update your PR description
- rebase also
LGTM

2020-05-28 21:15 UTC, descholar-ceo approved these changes

2020-05-29 08:14 UTC, Ugizwenayo-Divine approved these changes
Good job

2020-05-29 14:31 UTC, kipropbrian commented on src/services/request.service.js
> +  //     { where: { id: requestId } }
remember to remove comments

2020-05-31 13:37 UTC, the22mastermind approved these changes

2020-06-02 14:12 UTC, kipropbrian reviewed
why was package.lock deleted

2020-06-02 14:12 UTC, kipropbrian commented on tests/profile/profile.test.js
> +        console.log('==>', res.body);
No need for this

2020-06-03 12:22 UTC, kipropbrian approved these changes
Why are you deleting the package-lock?

2020-06-03 13:53 UTC, kipropbrian approved these changes

2020-06-05 08:55 UTC, merged