#171535709 integrate code climate
atlp-rwanda/stackup2-barefoot-backend pull request #8
Opened 2020-02-28 14:35 UTC by Ugizwenayo-Divine

#### What does this PR do?
- integrate code climate

#### Description of Task to be completed?
- add stackup2-barefoot repo on code climate
- add maintainability code climate badge in readme file

#### How should this be manually tested?
- you should see the maintainability badge in readme

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#171535709](https://www.pivotaltracker.com/story/show/171535709)

#### Screenshots (? if? appropriate)
N/A

2020-02-28 15:36 UTC, descholar-ceo requested changes
You did a good job, but it seems like you have some conflict with develop branch, could you solve it?

2020-02-28 19:38 UTC, descholar-ceo approved these changes

2020-03-01 18:57 UTC, muchristian approved these changes

2020-03-02 18:22 UTC, kipropbrian commented
Good job divine

2020-03-02 18:22 UTC, merged